### ISSUE TITLE
Add Find/Replace to Dynamic

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/synapse.core.net#58]
From CommandHandler, take:
```yaml
        - Find: ~~foo~~
          ReplaceWith: dummyValue
          Encoding: Base64
```
And enhance Dynamic:
```yaml
    Dynamic:
    - Name: key0
      Path: Arguments:Expressions[0]:ReplaceWith
      Find:
      Encoding: Base64
```
