### ISSUE TITLE
Fix Issues With Originating Array Data

### ISSUE THREAD

**Issue by GuyWaguespack** [SynapseProject/synapse.core.net#69]
- MyNewArray exists, but doesn't have a 7th value
- MyNewCrapArray doesn't exist at all.

```yaml
      ParentExitData:
      - Source: MyArray[0]:Value
        Destination: ExitData:MyNewArray[7]:Value
        Parse: false
      - Source: MyArray[0]:Value
        Destination: ExitData:MyNewCrapArray[0]:Value
        Parse: false
```
