### ISSUE TITLE
ParentExitData : Overwriting Entire Array Fails

### ISSUE THREAD

**Issue by GuyWaguespack** [SynapseProject/synapse.core.net#71]
Am albe to overwrite a single value with an Array (ReplaceMe) but not an entire Array (ReplaceMeArray).

```yaml
    Parameters:
      Type: Yaml
      Values: 
        SleepMilliseconds: 100
        ReturnStatus: Complete
        ExitData:
          Name: Action002-Data
          MyNextArray: Howdy
          MyNextValue: Howdy
          MyNewArray:
          - Fail
          - "222"
          - "333"
          - "444"
          ReplaceMe: Value
          ReplaceMeArray:
          - "AAA"
          - "BBB"
          - "CCC"
          - "DDD"
      ParentExitData:
      # Works When Destination Is A Value
      - Source: MyArray
        Destination: ExitData:ReplaceMe
        Parse: true
      # Fails When Destination Is An Array
      - Source: MyArray
        Destination: ExitData:ReplaceMeArray
        Parse: true
```
