### ISSUE TITLE
Dynamic - passing Array fails

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/synapse.core.net#72]
- plan
```yaml
Name: GenericSearch
Description: Perform A Generic Search Against The Active Directory
IsActive: true
Actions:
- Name: GenericSearch
  Handler:
    Type: Synapse.Handlers.ActiveDirectory:ActiveDirectoryHandler
    Config:
      Type: Yaml
      Values:
        Action: Search
        RunSequential: false
        ReturnObjects: true
        OutputType: Yaml
        PrettyPrint: true
        SuppressOutput: false
  Parameters:
    Type: Yaml
    Values:
      SearchRequests:
      - Filter: xxxxxxxx
        ReturnAttributes: xxxxxxxx
    Dynamic:
    - Name: filter
      Path: SearchRequests[0]:Filter
    - Name: attributes
      Path: SearchRequests[0]:ReturnAttributes
      Parse: true
```
- input
```json
{
  "Filter": "(|(member:1.2.840.113556.1.4.1941:=cn=TestUser001,ou=Synapse,dc=sandbox,dc=local)(distinguishedName=cn=TestUser001,ou=Synapse,dc=sandbox,dc=local))",
  "ReturnAttributes": [
    "name",
    "objectGUID",
    "objectSid"
  ]
}
```
