### ISSUE TITLE
Add Result structure to Sample Plan

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/synapse.core.net#76]
```yaml
Result:
  PId:
  Status:
  ExitCode:
  ExitData:
  BranchStatus:
  Sequence:
  Message:
  SecurityContext:
```
