### ISSUE TITLE
Update Result structure in Docs

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/synapse.core.net#77]
Diagram is out of date - wrong codes

```yaml
Result:
  PId:
  Status:
  ExitCode:
  ExitData:
  BranchStatus:
  Sequence:
  Message:
  SecurityContext:
```
