### ISSUE TITLE
Dynamic Parameter Replacement Fails When Parse=True

### ISSUE THREAD

**Issue by GuyWaguespack** [SynapseProject/synapse.core.net#92]
The replacement of an entire YAML section (parse = true) fails to generate or replace missing plan values under the following scenario unless the "dummyvalue" element is present : 

```yaml
Plan : 
  Parameters:
    Type: Yaml
    Values:
      Users:
      - Identity: 
        Properties:
          dummyvalue:
    Dynamic:
    - Source: properties
      Target: Users[0]:Properties
      Parse: true
```

**Comment by steveshortt** [comment]
The following test Plan produces replace _and_ merged results:

plan:
```yaml
Name: sampleDyno
Description: Parameter Substitution
Actions:
- Name: a0
  Handler:
    Type: Synapse.Core:EmptyHandler
  Parameters:
    Values:
      SleepMilliseconds: 0
      ReturnStatus: Complete
      Case0.0:
      - Identity: 
        Properties:
          dummyvalue:
      Case0.1:
      - Identity: 
        Properties:
      Case1.0:
        Identity:
        Properties:
          dummyvalue:
      Case1.1:
        Identity:
        Properties:
    Dynamic:
    - Source: properties
      Target: Case0.0[0]:Properties
      Parse: true
    - Source: properties
      Target: Case0.1[0]:Properties
      Parse: true
    - Source: properties
      Target: Case1.0:Properties
      Parse: true
    - Source: properties
      Target: Case1.1:Properties
      Parse: true
```

results:
```yaml
    StartInfo:
      Parameters: "SleepMilliseconds: 0\r\nReturnStatus: Complete\r\nCase0.0:\r\n- Identity: \r\n  Properties:\r\n    dummyvalue: \r\n    xyz: foo\r\n    abc: bar\r\nCase0.1:\r\n- Identity: \r\n  Properties:\r\n    xyz: foo\r\n    abc: bar\r\nCase1.0:\r\n  Identity: \r\n  Properties:\r\n    dummyvalue: \r\n    xyz: foo\r\n    abc: bar\r\nCase1.1:\r\n  Identity: \r\n  Properties:\r\n    xyz: foo\r\n    abc: bar\r\n"
      ParentExitData: 
  RunAs: 
  Parameters:
    Name: 
    Type: Yaml
    InheritFrom: 
    Uri: 
    Values:
      SleepMilliseconds: 0
      ReturnStatus: Complete
      Case0.0:
      - Identity: 
        Properties:
          dummyvalue: 
          xyz: foo
          abc: bar
      Case0.1:
      - Identity: 
        Properties:
          xyz: foo
          abc: bar
      Case1.0:
        Identity: 
        Properties:
          dummyvalue: 
          xyz: foo
          abc: bar
      Case1.1:
        Identity: 
        Properties:
          xyz: foo
          abc: bar
```
