### ISSUE TITLE
add option for default value in DynamicValue structure

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/synapse.core.net#95]

**Comment by steveshortt** [comment]
considering this layout:

```yaml
    Dynamic:
    - Source: kitten
      Target: Case0.0[0]:Properties
      Default:
        Value:
          foo: bar
          abc: 123
        AllowNull: true | false
      Parse: true
```
