### ISSUE TITLE
Add root resolution in Source for Yaml|Json

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/synapse.core.net#96]
```yaml
  Dynamic:
  - Source: Element:Path1:Path2
    Target: ...
  - Source: [need root]
    Target: ...
```
